# Generated by Django 5.1.7 on 2025-04-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_order_user_alter_ticket_movie_session_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
